apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2is-userstore-pvc
  namespace : wso2-iam-system
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50M
  storageClassName: standard