# permissions for end users to view wso2is.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: wso2is-viewer-role
rules:
  - apiGroups:
      - iam.wso2.com
    resources:
      - wso2is
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - iam.wso2.com
    resources:
      - wso2is/status
    verbs:
      - get
