# permissions for end users to edit wso2is.
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: wso2is-editor-role
rules:
  - apiGroups:
      - iam.wso2.com
    resources:
      - wso2is
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - iam.wso2.com
    resources:
      - wso2is/status
    verbs:
      - get
