apiVersion: iam.wso2.com/v1beta1
kind: Wso2Is
metadata:
  name: identity-server
spec:
  replicas: 2
  configurations:
    host: identityserver
    serviceType: ClusterIP
    superAdmin:
      username: admin
      password: admin
      createAdminAccount: true
    userStore:
      type: database_unique_id
    database:
      identityDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.1:3306/IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false
        username: admin
        password: '12345678'
      sharedDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.1:3306/IS_SHARED_DB?autoReconnect=true&amp;useSSL=false
        username: admin
        password: '12345678'
    keystore:
      primary:
        name: wso2carbon.jks
        password: wso2carbon
    authentication:
      authenticator:
        totp:
          enable: true
        sms_otp:
          enable: true
        email_otp:
          enable: false
  keystoreMounts:
    - name: samplekey1.jks
      data: sasadsadsadasdsdsadsadasdasdsd