apiVersion: wso2.wso2.com/v1beta1
kind: Wso2Is
metadata:
  name: wso2is-operator
spec:
  replicas: 3
  configurations:
    host: identityserver
    superAdmin:
      username: admin
      password: admin
      createAdminAccount: true
    userStore:
      type: database_unique_id
    database:
      identityDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.1:3306/IS_IDENTITY_DB?autoReconnect=true&amp;useSSL=false
        username: root
        password: '1234'
      sharedDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.99.1:3306/IS_SHARED_DB?autoReconnect=true&amp;useSSL=false
        username: root
        password: '1234'
    transport:
      https:
        properties:
          proxyPort: 443
    keystore:
      primary:
        name: wso2carbon.jks
        password: wso2carbon
    clustering:
      properties:
        KUBERNETES_API_SERVER: http://192.168.99.1:8001