apiVersion: iam.wso2.com/v1beta1
kind: Wso2Is
metadata:
  name: wso2is
  namespace: wso2-iam-system
spec:
  replicas: 2
  configurations:
    host: identityserver
    serviceType: ClusterIP
    superAdmin:
      username: admin
      password: admin
      createAdminAccount: true
    userStore:
      type: database_unique_id
    database:
      identityDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false
        username: admin
        password: 'admin'
      sharedDb:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false
        username: admin
        password: 'admin'
    keystore:
      primary:
        name: wso2carbon.jks
        password: wso2carbon