- op: replace
  path: /metadata/name
  value: prod-mysql

- op: replace
  path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
  value: prod-mysql-pv-claim

- op: replace
  path: /spec/template/spec/containers/0/volumeMounts/0/name
  value: prod-mysql-persistent-storage

- op: replace
  path: /spec/template/spec/containers/0/volumeMounts/1/name
  value: prod-init-sql

- op: replace
  path: /spec/template/spec/volumes/0/name
  value: prod-mysql-persistent-storage

- op: replace
  path: /spec/template/spec/volumes/1/name
  value: prod-init-sql

- op: replace
  path: /spec/template/spec/volumes/1/configMap/name
  value: prod-init-sql

- op: replace
  path: /spec/selector/matchLabels/app
  value: prod-mysql

- op: replace
  path: /spec/template/metadata/labels/app
  value: prod-mysql
