apiVersion: iam.wso2.com/v1beta1
kind: Wso2Is
metadata:
  name: wso2is
  namespace: wso2-iam-system
spec:
  replicas: 1
  configurations:
    host: wso2is.com
    server:
      hostname: wso2is.com
    serviceType: ClusterIP
    superAdmin:
      username: admin
      password: admin
      createAdminAccount: true
    userStore:
      type: database_unique_id
    database:
      identityDb:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/WSO2IS_IDENTITY_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false
        username: wso2carbon
        password: 'wso2carbon'
      sharedDb:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/WSO2IS_SHARED_DB?autoReconnect=true&amp;allowPublicKeyRetrieval=true&amp;useSSL=false
        username: wso2carbon
        password: 'wso2carbon'
    keystore:
      primary:
        name: wso2carbon.jks
        password: wso2carbon